[workspace]
resolver = "2"
members = ["*/rust/day-*"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
indicatif = { version = "0.17.7", features = ["rayon"] }
rayon = "1.8.0"
